### ISSUE TITLE
Improve documentation and code for bare(r) Vim experience

### ISSUE THREAD

**Issue by badosu** [onivim/oni#997]
This issue is not a request for a feature, but to track some points of work:

- Exposing documentation for Vim users expecting a Vim(er) experience with Oni on how to achieve it
- Identify and improve configuration for this
- Make the configuration actually remove overhead (incentivizing and keeping track of modularization of features)

Please let me know in the comments your thoughts and I'll update this description with the feedback.

@bryphe Let me know if this is pushing or overreaching, or even if there's a better way to organize this effort. I submitted this as a way to help making sure that users that want to use Oni without too many features have an easy (and performant) way to achieve it. I think a good chunk of Oni's audience in the future might be users with some Vim experience just wanting to get out of the terminal, and being able to enjoy some goodies out of it :-) .

- [ ] Create a Wiki page with recommended defaults and practices for barebones Oni
- [ ] Examine / improve (minimize) Oni's default VimL settings (#973)
- [ ]  Expose options on `config.js` (#976)
- [ ] Option to disable automatic autocomplete (#955)
- [ ] Option to restore Vim's index for tabs (#978)
- [ ] Make autopairs not be activated if it's not enabled (currently activated by the default and checking if it's enabled on keystrokes)

**Comment by bryphe** [comment]
Hi @badosu , did you mean to close this?

Sorry I missed replying to you - but the approach sounds great! I like the way you called this out.

I think this is definitely in-line with the direction we want to go - it should be easy to turn off Oni's features and opt-in to VimL plugins, if the user desires.
